disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - vertical_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Runr/AppDelegate.swift
  - Pods