disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - vertical_whitespace
  - force_try
  - force_cast
  - vertical_parameter_alignment

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Runr/AppDelegate.swift
  - Pods

line_length:
  warning: 150

nesting:
  type_level: 2